# Generated by Django 3.0.6 on 2020-05-25 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=120)),
                ('destination', models.CharField(max_length=120)),
                ('travel_date', models.DateField()),
                ('travel_class', models.CharField(max_length=120)),
                ('train_number', models.CharField(max_length=120)),
                ('destination_address', models.CharField(max_length=120)),
                ('destination_address_2', models.CharField(blank=True, max_length=120)),
                ('destination_address_3', models.CharField(blank=True, max_length=120)),
                ('destination_pin', models.CharField(max_length=120)),
                ('destination_state', models.CharField(max_length=120)),
                ('destination_city', models.CharField(max_length=120)),
                ('destination_post_office', models.CharField(max_length=120)),
                ('irctc_username', models.CharField(max_length=30)),
                ('irctc_password', models.CharField(max_length=30)),
                ('payoption', models.CharField(max_length=120)),
                ('paymethod', models.CharField(max_length=120)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=120)),
                ('person_age', models.IntegerField()),
                ('gender', models.CharField(max_length=120)),
                ('preference', models.CharField(default='No Preference*', max_length=120)),
                ('nationality', models.CharField(default='IN', max_length=120)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logged_in_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
