# Generated by Django 3.0.6 on 2020-05-25 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completion_status', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=120)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Booking')),
            ],
        ),
    ]
